name: jl-healthfitness
favicon: null
layout_spectrum: 0.248869952512905
typography_spectrum: 0.613993369275704
title: 'Jamie Luke Health & Fitness'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-50143445-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebd63e'
    - '#585857'
    - '#998f4b'
    - '#c1b245'
    - '#f8f0b9'
  brandStrength: 1
  lightness: 0.9663713278714567
  saturation: 0.625
  rhythmicContrast: 0.3075937039684504
purpose: []
